### ISSUE TITLE
small warning after fresh install

### ISSUE THREAD

**Issue by daxaxelrod** [growthbook/growthbook-react#4]
from version: `"@growthbook/growthbook-react": "^0.7.0",`

```bash
warn Package @growthbook/growthbook-react has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/davidaxelrod/Documents/boldvoice/w/node_modules/@growthbook/growthbook-react/package.json
```

**Comment by jdorn** [comment]
Looks like it's a bug with React Native.  https://github.com/react-native-community/cli/issues/1168

Does it still work or does that warning stop the SDK from loading entirely?

**Comment by daxaxelrod** [comment]
Works just fine, just wanted to make you aware :D. Thanks for the link
